# Generated by Django 4.0.4 on 2022-04-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_application_dealer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dealer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
