# Generated by Django 4.0.4 on 2022-04-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_application_dealer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dealer_id',
            field=models.IntegerField(null=True),
        ),
    ]
